use_frameworks!

target 'ContactCard_Example' do
  pod 'ContactCard', :path => '../'

  target 'ContactCard_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
